### ISSUE TITLE
VOICE_CONNECTION_TIMEOUT

### ISSUE THREAD

**Issue by RiverTeacher** [chebro/discord-voice-recorder#25]
an error message appears.
/workspace/discord-voice-recorder/node_modules/discord.js/src/client/voice/VoiceConnection.js:303
      this.emit('error', new Error(reason));
                         ^

Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (/workspace/discord-voice-recorder/node_modules/discord.js/src/client/voice/VoiceConnection.js:303:26)
    at /workspace/discord-voice-recorder/node_modules/discord.js/src/client/voice/VoiceConnection.js:324:61
    at Timeout.<anonymous> (/workspace/discord-voice-recorder/node_modules/discord.js/src/client/BaseClient.js:82:7)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  [Symbol(code)]: 'VOICE_CONNECTION_TIMEOUT'
}
how can I fix it?

**Comment by AlexR1712** [comment]
Same problem here
